{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "datadog-confluent.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
  labels:
    {{- include "datadog-confluent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/stats
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
      - componentstatuses
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - datadogtoken
      - datadog-leader-election
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["create"]
  - nonResourceURLs:
      - "/metrics"
      - "/healthz"
      - "/livez"
      - "/readyz"
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
  labels:
    {{- include "datadog-confluent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
  - kind: ServiceAccount
    name: datadog-agent
    namespace: {{ .Values.namespace }}
{{- end }}
