apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: confluent
spec:
  type: NodePort
  selector:
    platform.confluent.io/type: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
