apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datadog

helmCharts:
  - name: datadog
    releaseName: datadog
    version: 3.149.2
    repo: https://helm.datadoghq.com
    valuesFile: values.yaml
    namespace: datadog

resources:
  - ../base/
