apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-kafka-rest:7.9.0
    init: confluentinc/confluent-init-container:2.10.0
  podTemplate:
    labels:
      env: local-poc
      service: kafka-restproxy
      component: kafkarestproxy
      team: data-platform
    annotations:
      ad.datadoghq.com/kafkarestproxy.check_names: '["confluent_platform"]'
      ad.datadoghq.com/kafkarestproxy.init_configs: '[{"is_jmx": true, "collect_default_metrics": true, "service_check_prefix": "confluent", "new_gc_metrics": true, "collect_default_jvm_metrics": true}]'
      ad.datadoghq.com/kafkarestproxy.instances: '[{"jmx_url":"service:jmx:rmi://%%host%%:7203/jndi/rmi://%%host%%:7203/jmxrmi","name":"rest_proxy_instance","tags":["component:kafkarestproxy","env:local-poc","service:kafka-restproxy","team:data-platform"]}]'
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    envVars:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: _JAVA_OPTIONS
        value: "-Djava.rmi.server.hostname=$(MY_POD_IP)"
  configOverrides:
    jvm:
      # Override CFK's default local-only JMX so the Datadog DaemonSet agent can connect.
      - -Dcom.sun.management.jmxremote.local.only=false
      - -Dcom.sun.management.jmxremote.host=0.0.0.0
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
